<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    protected $except = [
      'saveCompany',
      'loginValidate',
      'updateCompany',
      'saveDelivery',
      'getDeliverDetailsByDeliveryId',
      'getDeliveryByStatus/*',
      'getDeliveryById',
      'updateDelivery',
      'saveDeliverDetail',
      'createCity',
      'getCity',
      'getCityInfo',
      'updateCity',
      'deleteCity',
      'createUnit',
      'getUnit',
      'showUnitInfo',
      'updateUnit',
      'deleteUnit',
      'createGoodRecipt',
      'getGoodReceipt/*',
      'showGoodReceiptInfo',
      'updateGoodReceipt',
      'deleteGoodReceipt',
      'createGoodReciptDetails',
      'getGoodReceiptDetail',
      'getGoodReceiptInvoice',
      'getGoodInOutByCompanyId',
      'saveStatementCarList',
      'createOrder',
      'showGoodReceiptDetailInfo',
      'updateGoodReceiptDetail',
      'deleteGoodReceiptDetail',
      'getOrder/*',
      'getOrderDetail',
      'deleteOrder',
      'getOrderNoBycompanyId',
      'getGoodReceiptByorderNo',
      'getOrderDetailsByorderId',
      'updateOrderByorderId',
      'getVipCustomer',
      'getVipCustomerInfo',
      'getStatmentCarList',
      'createUser',
      'getUser',
      'deleteUser',
      'showUserInfo',
      'updateUser',
      'getRule',
      'createRule',
      'showRuleDetail',
      'updateRule',
      'deleteRule',
      'getCompany',
      'resetPassword',
      'createCompanyByGoogle',
      'saveUserInfoFacebook',
      'updateOrderBygoodReceiptId'
    ];
}
